### PR TITLE
Project fixes

### PR DESCRIPTION
**Pull request by HaoZeke**
Hi everyone, I have added instructions to reproduce the site locally, and also made some other project specific fixes.

### CODE REVIEW

**Comment by davidcarlisle** [comment]
Thank you for the PR.

We will probably hold off merging at present as the site styling is currently being looked at by our web designer @jonasjacek and all such issues as jekyll themes or in fact use of jekyll itself are still open. We used a minimal theme initially specifically to not inhibit later restyling.

On the title, use of learnlatex.org to "brand" the tutorial to this site was deliberate: your suggested change to "Learn LaTeX" is a far more generic phrase (although again such site branding details are yet to be finalised).

However I'll keep this open and we can see where we are after the site has been restyled

**Comment by HaoZeke** [comment]
Oh the `jekyll` version is way too old, as is the theme, the newest version is 4.x and this runs a theme which needs 1.x or something (in the `Gemfile.lock`). I can revert the title commit, but it might still make sense to merge the rest right now so new contributors can build the setup locally.

**Comment by davidcarlisle** [comment]
I would expect that most contributors would use gh-pages. Personally I see one of the main advantages of gh-pages hosting is that contributors do not require any software install. The current pages and translations have been developed  without using a local jekyll build and while I agree it would be good to document the configuration required for a local build I don't think that will be the main build mechanism for most people.  So all I meant by my first comment is that we can hold off  distributing and documenting a local build configuration until the final styling is decided, so we don't have to keep it up to date as things are updated.

**Comment by HaoZeke** [comment]
I'm not sure this should take that long to maintain, but in any case, good luck!!

**Comment by joulev** [comment]
I think future contributors may find this guide helpful, because some may use a local deployment rather than rely on GH Page all the time (I also use a local Jekyll build as I sometimes work offline). Don’t worry, it is by no means useless :)

**Comment by davidcarlisle** [comment]
@joulev  yes sure I think the idea to document a local jekyll build is good but the current theme is just the simplest most basic theme gh pages provides, we chose it so that it could be changed when we get round to really styling the site, so I just suggest holding off waiting until the site styling is done then document whatever we end up with:-)

**Comment by joulev** [comment]
> @joulev  yes sure I think the idea to document a local jekyll build is good but the current theme is just the simplest most basic theme gh pages provides, we chose it so that it could be changed when we get round to really styling the site, so I just suggest holding off waiting until the site styling is done then document whatever we end up with:-)
> 
> 

@davidcarlisle Yes, so many things have to be settled when the design of the site is decided. But for now, at least, this guide is good ;)

**Comment by jonasjacek** [comment]
This seems a little outdated. 
I'd keep the updated `AUTHORS` and `CONTRIBUTION` files. Suggested changes to `.gitignore` are already included. Everything else feels odd to do now / outdated.

**Pull request closed without merging**
