### PR TITLE
Vietnamese translations

### PR DESCRIPTION
**Pull request by joulev**
This is to keep track of Vietnamese translations of future commits in the `en` directory.

### CODE REVIEW

**Comment by davidcarlisle** [comment]
hi thanks for this, let us know when you want us to merge,

**Comment by joulev** [comment]
@davidcarlisle Perhaps only when the site is released or the text is completed. Merging this early is okay of course but I don't want to create too many PRs for the same purpose :)

**Comment by davidcarlisle** [comment]
@joulev  Hi I have removed the "don't translate" banner from lesson-15 and more-15. 

If you could find time to translate them I would merge this PR and we could have en and vi in place versions complete before tug2020 in a couple of weeks?

**Comment by joulev** [comment]
@davidcarlisle Thanks. I have plenty of time tomorrow, so I will have a look ;)

**Comment by joulev** [comment]
oh wait don't merge yet. I still have some clean-up to do.

**Comment by joulev** [comment]
@davidcarlisle I think everything is okay now.

**Comment by joulev** [comment]
@davidcarlisle Hi. This PR can be merged now :)

**Comment by davidcarlisle** [comment]
Thanks a lot, all merged.

**Pull request merged**
