### PR TITLE
Vietnamese translations of meta descriptions (partially fix #101)

### LINKED ISSUE #101: Add translations of toc-anchor-text and toc-description
With the design updates, all `en` lessons now have `toc-anchor-text`, `toc-description` and `description` at the top of every lesson `.md` file that needs translation.  This issue is for keeping track of the ones already added (only completed translations listed):

- [x] `pt` @PhelypeOleinik 
- [x] `vi` @joulev 
- [x] `fr` @jejust 
- [ ] `es` @fersdt @EmanuelPrima 
- [ ] `tr`
- [ ] `de`

(check your box when completed... if github allows :)

### PR DESCRIPTION
**Pull request by joulev**
* #101 
* I also fixed some translation mistakes in `/_data`.

### CODE REVIEW

**Comment by jonasjacek** [comment]
Thank you!

**Comment by davidcarlisle** [comment]
@joulev  Thanks for all the translations so far:-)

As you may have seen the new design has now gone live at the main site, so leaving some English texts on the main page
https://www.learnlatex.org/vi/


 I have updated
https://www.learnlatex.org/TRANSLATIONS
to hopefully give correct instructions for the new layout, but if anything is not clear please ask (or make a PR adding text there if I forgot anything)

**Comment by joulev** [comment]
@davidcarlisle Thanks for the reminder.

I will have a look at files outside the `/vi` directory as soon as possible.

As I have not been following this repo closely recently, I suppose there are no changes in the `/vi` directory that requires translations. @jonasjacek Am I right about this?

**Comment by jonasjacek** [comment]
Dear @joulev, I didn't change any contents. I've added site wide translations (done with a translate tool) in `/_data/translations.yml`. It would be good if you could review these for correctness, if you haven't done it before. 

Otherwise /vi looks quite complete to me.

**Comment by joulev** [comment]
> Dear @joulev, I didn't change any contents. I've added site wide translations (done with a translate tool) in `/_data/translations.yml`. It would be good if you could review these for correctness, if you haven't done it before. 
> 

@jonasjacek In that case, all is fine now. Thanks for the clarification.

**Comment by joulev** [comment]
@jonasjacek Today I randomly navigated some pages, and noticed that in at least one location, there are some new paragraph classes, as `.summary` and `.hint` in `/en/extra-01.md`

https://github.com/learnlatex/learnlatex.github.io/blob/331f9cc770114f462cedef43c1f199bade2814ca/en/extra-01.md#L12-L22

Maybe I missed the commits adding those classes.

Can you list all the new classes and where they appear so that I can change the vi version accordingly? Thank you.

**Comment by davidcarlisle** [comment]
@joulev  checking the en pages I think all lessons have exactly one instance of `summary` and  0 or more `hint` and no other html markup giving css classes.

the index file has more:

```
$ grep -o 'class *=[^>]*' *md
extra-01.md:class="summary"
extra-01.md:class="hint"
index.md:class="heading__introduction"
index.md:class="text-columns"
index.md:class="text-columns__heading"
index.md:class="text-columns__heading"
index.md:class="heading__toc" id="toc"
index.md:class="paragraph__toc"
index.md:class="heading__toc"
index.md:class="lessons-toc"
language-01.md:class="summary"
lesson-01.md:class="summary"
lesson-02.md:class="summary"
lesson-02.md:class="hint"
lesson-03.md:class="summary"
lesson-03.md:class="hint"
lesson-03.md:class="hint"
lesson-04.md:class="summary"
lesson-05.md:class="summary"
lesson-06.md:class="summary"
lesson-07.md:class="summary"
lesson-08.md:class="summary"
lesson-09.md:class="summary"
lesson-10.md:class="summary"
lesson-10.md:class="hint"
lesson-11.md:class="summary"
lesson-12.md:class="summary"
lesson-13.md:class="summary"
lesson-14.md:class="summary"
lesson-14.md:class="hint"
lesson-15.md:class="summary"
lesson-16.md:class="summary"
lesson-16.md:class="hint"
lesson-16.md:class="hint"
lesson-16.md:class="hint"
```

**Pull request merged**
