### PR TITLE
First design update

### PR DESCRIPTION
**Pull request by jonasjacek**
I've merged a first design update and informed in README.md about the plan to constantly merge `master` with `design`. I am curios if the everything works well within the GitHub Pages env. 

**Note:** 
I have removed `.markdown-body` dive and class. Fonts should now be scalable. Size and font may change though.

### CODE REVIEW

**Comment by davidcarlisle** [comment]
Looks good to me, thanks:-)
tested on gh pages at my copy at https://davidcarlisle.github.io/ll/
do you want to merge the individual commits or squash?
I think we should accept the PR then I'll do another general check on it in-place.

**Comment by davidcarlisle** [comment]
one thing I noticed previously, don't you need `layout: learnlatex` in the yml frontmatter of each page, or have you changed teh default layout to that from `default.html` somewhere that I missed?

**Review by davidcarlisle — APPROVED** [review]
comments left on the main PR page

**Comment by davidcarlisle** [comment]
it won't affect the main site but the path to the woff fonts breaks on forks as for other links, I get

downloadable font: download failed (font-family: "roboto_light" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: https://davidcarlisle.github.io/assets/fonts/roboto_light.woff2

 as it needs to be https://davidcarlisle.github.io/ ll /assets/fonts/roboto_light.woff2

There must be a way to template the `src: url` css paths in style.scss to pick up the root of the site.

**Comment by davidcarlisle** [comment]
oh the style.scss file is run through jekyll so the smae fix solves it, three instances of

```
-  src: url('/assets/fonts/roboto_light_italic.woff2') format('woff2');
+  src: url({{'/assets/fonts/roboto_light_italic.woff2'| relative_url}}) format('woff2');
```

make it work with roboto fomts now at my copy
https://davidcarlisle.github.io/ll/en/lesson-11

**Comment by davidcarlisle** [comment]
The roboto font appears to have problems with Vietnamese

image

Certain accented characters are presumably not in the font so are falling through to Times Roman

**Comment by joulev** [comment]
I think the links need to be more blue. The current colour is a bit too similar to black when displayed on my screen.

image

image

**Comment by joulev** [comment]
> The roboto font appears to have problems with Vietnamese

I don't know which source did you use for Roboto but I think [the Roboto on Google Fonts supports Vietnamese very well](https://fonts.google.com/specimen/Roboto?query=roboto&preview.text=trong+h%E1%BA%A7u+h%E1%BA%BFt+c%C3%A1c+tr%C6%B0%E1%BB%9Dng+h%E1%BB%A3p&preview.text_type=custom).

image

**Comment by stone-zeng** [comment]
The LaTeX logo can be much better if adjust the css for "A" as:

```css
element.style {
    font-variant: small-caps;
    font-weight: 600;
    vertical-align: .4ex;
    margin-left: -.25em;
    margin-right: -.05em;
}
```

image

However, these values may be dependent on the actual font that used here.

**Comment by Skillmon** [comment]
For me (on @davidcarlisle's demo-page) the logo gets cut-off on the right end:


learnlatexlogo

**Review by davidcarlisle — COMMENTED** [review]
Originally I approved thinking it would be best to show things on the main site to allow more people to comment even though things still to change in-place, but perhaps best to fix the Vietnamese and SVG font issues first before moving to main site. People seem to be commenting based on my copy

**Comment by davidcarlisle** [comment]
> 
> 
> For me (on @davidcarlisle's demo-page) the logo gets cut-off on the right end:
> 
> learnlatexlogo

I think the svg is relying on a local CMU Serif, @jonasjacek  can we replace the fonts by svg paths here?

**Comment by jonasjacek** [comment]
Let's not merge and publish to master for now. I am overwhelmed with messages. I am aware of 95% of the things that are being mentioned.

**Comment by davidcarlisle** [comment]
I flipped my github-pages copy back to the master branch as well.

**Pull request closed without merging**
