### PR TITLE
Vietnamese translation [4th]

### PR DESCRIPTION
**Pull request by joulev**
The fourth PR on stuff inside `/vi`. This is a work in progress, please tell me when it is fit to merge this.

This PR includes Vietnamese translations for
* description text of the ACE editor
* #74

### CODE REVIEW

**Comment by davidcarlisle** [comment]
er...

> The fourth PR on stuff inside /vi. This is a work in progress, please tell me when it is fit to merge this.

as far as I know you are the only one here that can read this, we can't really review it, I'll merge it when you say it's OK.

Or if you mean is the english text for those parts stable. Then probably the answer is yes, although as you see we are getting several gh issues posted as the site becomes more noticed.

**Comment by joulev** [comment]
@davidcarlisle I mean that PRs like this should be closed in a way that the merged translation is relatively up to date with the original text but there aren’t too many PRs. So maybe once a month or once every two months... What do you think?

**Comment by davidcarlisle** [comment]
If you (or any translator) has done the work I don't think there is a problem with merging it whenever you are ready.

I think we agree though that a 1-2 month check is a reasonable timeframe so rather than mailing translators on every checkin I'd like to think that every month or so we could automatically generate a link to a github diff page showing all the changes in /en since the last merge in that language directory.

**Comment by davidcarlisle** [comment]
Thank you  for working on learnlatex.org translations.
You may have seen already if watching the repository but just a note
to say that we have extended lesson-06 and more-06 to add descriptions
of defining commands with \newcommand and \NewDocumentCommand

https://github.com/learnlatex/learnlatex.github.io/commit/463d181301d667b10bf23c164f9d5ae15371877e

**Comment by joulev** [comment]
@davidcarlisle Thanks, will do it asap.

**Comment by davidcarlisle** [comment]
@joulev  That was quick, thanks!

 You still have this flagged as draft but should I merge now, the number of changes have built up?

**Comment by joulev** [comment]
@davidcarlisle Oh, yes, I have even forgotten that this is a draft :)

**Pull request merged**
