### PR TITLE
Missing ` in help page

### PR DESCRIPTION
**Pull request by joulev**

### CODE REVIEW

**Comment by joulev** [comment]
Found these two little typos while reading the en/help page.

**Comment by joulev** [comment]
Already fixed in https://github.com/learnlatex/learnlatex.github.io/commit/f0ae91a8a3f8593b36789af102691c1db92b972d, closing.

**Comment by davidcarlisle** [comment]
@joulev  sorry I completely missed this PR for some reason.

**Comment by joulev** [comment]
@davidcarlisle No problems :) at the time of closing it had a merge conflict anyway.

**Pull request closed without merging**
