### PR TITLE
Add Vietnamese translation

### PR DESCRIPTION
**Pull request by joulev**
🇻🇳

The language-specific lessons will be added later. Currently vi/language-01.md is only a "placeholder" with a simple example. However all other files have been translated.

I am not sure if I should make any modifications to the CHANGELOG.

Also this is my first ever GH pull request. I hope I have got everything working the right way, but that is not guaranteed (sorry).

### CODE REVIEW

**Comment by joulev** [comment]
Oh, there is a conflict reported in `_config.yml`. Sorry I have absolutely no idea about that, could you please tell me what happened?

**Comment by davidcarlisle** [comment]
@joulev I resolved that conflict manually here I think it was just that your vi line conflicted with an addition of a final end-of-line being added to the end of the file in the master branch so no real problem. Thanks for this

**Comment by davidcarlisle** [comment]
Thanks a lot for this, it is live at https://www.learnlatex.org/vi/

**Comment by joulev** [comment]
@davidcarlisle Great, thanks!

**Comment by joulev** [comment]
@davidcarlisle It seems like this PR creates a branch `joulev-master`. I am not good at git, could you please explain for me what has happened here? And will deleting `joulev-master` do any harm?

**Comment by davidcarlisle** [comment]
@joulev I'll look later: probably best not to delete anything just yet:-)

**Comment by joulev** [comment]
@davidcarlisle I can’t delete it anyway :) just thinking that its presence is quite weird.

**Comment by davidcarlisle** [comment]
@joulev  oh I see what you mean: sorry, joulev-master was me merging your original PR.

There were some merge conflicts, possibly just cname, I forget, so I couldn't accept your PR using the website merge PR interface.

So the way that works is that I checked out the master branch from your repository to a branch arbitrarily called joulev-master, fixed up any merge conflicts so I could merge from that branch to the master here then push it all to github. Actually I could have left joulev-master branch local to my checkout and not pushed back but I probably accepted it making an upstream branch in some default.

So yes it can be deleted, I'll clean up later.

**Comment by joulev** [comment]
Oh, I see. Thanks for the detailed explanation!

**Pull request merged**
