### PR TITLE
Catalan translation finished

### PR DESCRIPTION
**Pull request by joanillo**
Catalan translation is finished. May be few changes from people who want to review this translation. But it is possible to proceed with the publication of this translation. Thanks

### CODE REVIEW

**Comment by davidcarlisle** [comment]
Thanks, there are some merge conflicts but I can fix (lang:en mostly I think)

**Comment by davidcarlisle** [comment]
@joanillo  actually not being able to read the text reliably I'm not that confident of doing the merge, can I let you do that I don't want to mess up your text? (I just tried locally and got more conflicts so i aborted and didn't push back to githib)

**Comment by davidcarlisle** [comment]
sorry about that, at least some of the conflicts were because I fixed some `lang:` and `permalink:` fields in the metadata to have ca rather than en as it turns out that having two files with the same fields checked in had some "interesting" effects on the site navigation, so I directly changed them on the main branch here so the site built correctly. I should probably have pinged you at the time.

**Comment by davidcarlisle** [comment]
@joanillo  Thanks a lot!

 I resolved all the conflicts locally in the end so I will close this PR.  

After you started the transation I added a new settings page which I don't think got translated (unless I dropped it somewhere in the merge) Also the end section of the help page has been extended with modified settings for make4ht and mention of latexml and lwarp, I added that back in English.

So could you check 

https://www.learnlatex.org/ca/settings

https://www.learnlatex.org/ca/help

and more generally check everything as you expect on the site.

**Comment by davidcarlisle** [comment]
@joanillo also (unless you have objection to being listed) would you like to add yourself to 

https://www.learnlatex.org/AUTHORS

(most of us have used real names rather than github names but any name is OK:-)

**Comment by joanillo** [comment]
thank you very much,
i will clone again the whole project and translate changes i settings and
help.
I will wait also for few feecbakcs from my collegues.
Att,
Joan Quintana

Missatge de David Carlisle ***@***.***> del dia dc., 21
d’abr. 2021 a les 8:55:

**Pull request closed without merging**
