### PR TITLE
WIP: Marathi translation

### PR DESCRIPTION
**Pull request by NiranjanTambe**
This is a PR for Marathi translation.

It is a WIP. Translations for 5 chapters and all the `more's are pending. I am working on them, but I thought it would be good to create a PR, so that the maintainers can review the current code and check if everything is going correctly. I am trying to complete the translation before 27 as it is the [Marathi language day](https://en.wikipedia.org/wiki/Marathi_Language_Day)! I would be very glad if this work gets released on that day. Of course it's not a necessity. It just seems to be a relevant day for publishing this work. I would love to hear thoughts about this from the maintainers of the site.

### CODE REVIEW

**Comment by davidcarlisle** [comment]
Thanks! I think this looks OK I pulled locally and fixed up restoring CNAME and deleting the old style list of languages in _config.yml which isn't used in the new design, but I think it looks good to merge from here now.

**Comment by davidcarlisle** [comment]
Live at https://www.learnlatex.org/mr/

**Comment by NiranjanTambe** [comment]
Thanks for the merge @davidcarlisle.

Unfortunately this was a WIP PR, but never mind I've added another one here -

https://github.com/learnlatex/learnlatex.github.io/pull/142

Kindly merge this too.

Also I really don't understand what to do with the CNAME file. Can you please help?

Thanks 😄

**Comment by davidcarlisle** [comment]
thanks I can sort the merge note you can mark a PR as draft in the github page if you don't want it to be merged yet, although actually doing the  partial merge first is fine.

on CNAME it is a pain (there are several feature requests at github to make it easier) but currently ideally it is simplest if you put it back saying www.learnlatex.org  before making the PR but then you need to delete it again or your fork "steals" the name.
But it doesn't really matter if you leave it deleted we just merge here then add it back, which is simpler in some ways.

**Comment by NiranjanTambe** [comment]
Okay, thanks.

**Pull request merged**
