### PR TITLE
Add user settings

### PR DESCRIPTION
**Pull request by davidcarlisle**
This PR adds a new user settings file en/settings.md  (with rough translations for French , and provided Portuguese) other languages being a copy of the english text.

This allows user settable defaults for the TeX engine to be used, the return mechanism and the default theme for the embedded editor.

As the user defaults are stored in cookies there is an accept/delete mechanism in place and the settings are disabled until the cookie mechanism is accepted. A new privacy policy page lang/privacy.md is also added.

Links to the settings and privacy pages are added to the top and bottom navigation respectively so new "Settings" and "Privacy" texts appear in the translations file (mostly untranslated).

As the new files affect all translations I am adding the translations label and pinging the main translators here, just for information. However the main addition for this PR is the user settings feature see issue #58 not specifically related to translations.

de @sieversMartin @Skillmon
en @davidcarlisle @josephwright
es @fersdt
fr @jejust
ja @wtsnjp
kr @fermat39
mr @NiranjanTambe
pt @PhelypeOleinik
tr @erdaldogan
vi @joulev
zh @stone-zeng

### CODE REVIEW

**Comment by josephwright** [comment]
I've merged here - I wonder if we need to adjust lesson 2 to point out that HTML output is available?

**Comment by davidcarlisle** [comment]
> 
> 
> I've merged here - I wonder if we need to adjust lesson 2 to point out that HTML output is available?


I suspect not, or at least not simply say it is available.  All the examples have been tested at both Overleaf and texlive.net but the make4ht output is more like the "excercises":  a rather looser invitation to experiment. Most of the lesson examples work quite well some less so but by the time you get to extra01 it is struggling.

**Comment by davidcarlisle** [comment]
@josephwright  But I should probably mention the settings as an alternative to !TeX comments in the help page where discuss pdf and html return

**Comment by josephwright** [comment]
@davidcarlisle  Yes, something would be good

**Comment by joulev** [comment]
@davidcarlisle 

> User Data
> 
> LearnLatex.org requires no user login and stores no user-specifc data. [...]

I think the "LearnLatex.org" part should be written as either "LearnLaTeX.org" or "learnlatex.org" or "Learn LaTeX" instead.

**Comment by joulev** [comment]
A few words after that, I can also see "github pages", which should be "GitHub Pages" instead.

Sorry for being too picky on service names, but in my opinion they should always be written with the correct capitalisation unless in special cases (the whole site is in lowercase/uppercase etc).

**Comment by davidcarlisle** [comment]
@Joulev pushed
   4eec14blev..9cc9f1e  main -> main

**Pull request merged**
